name: erupa_agent_v2
description: erupa agent rebrand.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  iconly: ^1.0.1
  flex_color_scheme: ^7.0.5
  google_fonts: ^4.0.4
  top_snackbar_flutter: ^3.0.0+1
  gradient_like_css: ^1.0.1
  animate_do: ^3.0.2
  flutter_animate: ^4.1.1+1
  animations: ^2.0.7
  equatable: ^2.0.5
  intl_phone_number_input: ^0.7.3+1
  flutter_localizations:
    sdk: flutter
  intl: any
  pinput: ^2.2.31
  flutter_card_swiper: ^5.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0
  path_provider: ^2.0.14
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path: ^1.8.2
  get_it: ^7.5.0
  http: ^0.13.6
  sliding_up_panel: ^2.0.0+1
  firebase_auth: ^4.2.2
  ionicons: ^0.2.2
  flutter_svg_provider: ^1.0.3
  flutter_svg: ^1.1.6
  hive_generator: ^2.0.0
  firebase_messaging: ^14.6.1
  country_code_picker: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.6.2


flutter:
  # Localization
  #  generate: true

  # Designs
  uses-material-design: true

  assets:
    #    - assets/images/
    - assets/svgs/
    - assets/gifs/
